{% set name = "datasketches" %}
{% set version = "5.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datasketches-{{ version }}.tar.gz
  sha256: aa040ccb0d41f0973306b34c293fe1c48f9da0faddbf66b4a2ad9cfa172719cc

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    #- {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - cmake >=3.16
    - numpy <2.0
    - nanobind >=1.6
    - pip
    - make
    #- pybind11 >=2.6.0
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - datasketches
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://datasketches.apache.org
  dev_url: https://github.com/apache/datasketches-cpp/tree/master/python
  summary: The Apache DataSketches Library for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - rxm7706
