{% set name = "datasketches" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datasketches-{{ version }}.tar.gz
  sha256: 6a57e4d1e93ccf1035604e3d9181dbe490281673833ce5be477c197b1195c840

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - wheel
    - setuptools >=30.3.0
    - cmake >=3.16
    - make
    - pybind11 >=2.6.0
    - pip
  run:
    - python
    - numpy

test:
  imports:
    - datasketches
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://datasketches.apache.org
  dev_url: https://github.com/apache/datasketches-cpp/tree/master/python
  summary: The Apache DataSketches Library for Python
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - rxm7706
